### ISSUE TITLE
Adblock?

### ISSUE THREAD

**Issue by GanerCodes** [idkr-client/idkr#66]
Can this be added?

**Comment by Mixaz017** [comment]
If you just want to hide ads, it's possible with userscripts (or css). Not planned to be a built-in feature for now.

**Comment by GanerCodes** [comment]
is there a way to launch it with a crx extension somehow attached to it? or compiled in?

**Comment by Mixaz017** [comment]
To add some more info: "True" adblocking in a form of blocking web requests for ad URLs and fixing broken layout caused by missing requests, is a lot of effort. Especially if we had to maintain those ad URLs (which is definitely never going to happen). Fortunately there are some publicly available filter lists such as https://easylist.to/ , but we have to make a parser for it. There was https://github.com/bbondy/abp-filter-parser but it seems to be unmaintained for 5 years. If someone is motivated enough to implement a parser for the client, built-in adblocking might happen.

**Comment by GanerCodes** [comment]
alright I got an adblocker working. The extension method didn't do anything but this package works flawlessly https://github.com/ghostery/adblocker/tree/master/packages/adblocker-electron#usage
